name: all_my_examples
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Config
  envied: ^0.5.4+1

  # Core
  get_it: ^8.0.1
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Generators
  envied_generator:
  build_runner:
  

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/images/

 